### ISSUE TITLE
KickAss 5.0 support

### ISSUE THREAD

**Issue by er0l** [p-a/kickass-cruncher-plugins#3]
Plugin does not work when used with new KickAss version 5.0.

Error while compiling code that has 
.plugin "se.triad.kickass.CruncherPlugins"
included results with:

`Exception in thread "main" java.lang.NoClassDefFoundError: cml/kickass/plugins/interf/IArchive
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at kickass.pass.asmnode.directives.PluginDirective.executeMetaRegistrations(Unknown Source)
	at kickass.pass.asmnode.metanodes.AsmNodeList.executeMetaRegistrations(Unknown Source)
	at kickass.pass.asmnode.metanodes.NamespaceNode.executeMetaRegistrations(Unknown Source)
	at kickass.KickAssembler.assemble(Unknown Source)
	at kickass.KickAssembler.execute(Unknown Source)
	at kickass.KickAssembler.main(Unknown Source)
	at cml.kickass.KickAssembler.main(Unknown Source)`

**Comment by p-a** [comment]
Yes, this is in the works. 👍

**Comment by p-a** [comment]
Hi, 
Just released 2.0-beta-1 which should take care of your problems.
None of the new stuff KickAss5 offers are yet supported, but will be in a later release.
