### ISSUE TITLE
Can't get this to run, any advice?

### ISSUE THREAD

**Issue by furroy** [p-a/kickass-cruncher-plugins#4]
Windows 10
Kickasm V5.9
Java version "1.8.0_231"

`C:\Users\furro\OneDrive\Documents\hired2>java -verbose:class -cp "kickass-cruncher-plugins-2.0.jar;KickAss.jar" kickass.KickAssembler src/build_disk.asm -define AUTO_WIN   1>derp.txt  || goto :error
Exception in thread "main" java.lang.NoSuchMethodError: java.util.List.of(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/List;
        at se.triad.kickass.exomizer.RawExomizer.getParams(RawExomizer.java:88)
        at se.triad.kickass.AbstractSegmentCruncher.<init>(AbstractSegmentCruncher.java:25)
`

**Comment by furroy** [comment]
so finally sorted this out on my own, a normal version of java won't do, needs jdk 13+
